require 'json'

f = File.new 'deploy/node.json'
s = f.read
f.close
j = JSON.load s

Vagrant::Config.run do |config|

  config.vm.box = "base"
  config.vm.customize do |vm|
    vm.memory_size = 512
  end

  # Forward a port from the guest to the host, which allows for outside
  # computers to access the VM, whereas host only networking does not.
  
  config.vm.forward_port "http", 80, 8080
  config.vm.forward_port "mysql", 3306, 3333

  # Share an additional folder to the guest VM. The first argument is
  # an identifier, the second is the path on the guest to mount the
  # folder, and the third is the path on the host to the actual folder.
  
  # config.vm.share_folder "v-data", "/vagrant_data", "../data"

  # Enable provisioning with chef solo, specifying a cookbooks path (relative
  # to this Vagrantfile), and adding some recipes and/or roles.
  
  config.vm.provision :chef_solo do |chef|
    chef.cookbooks_path = "deploy/cookbooks"
    chef.add_recipe "coreque::default"
    chef.json = j
  end

end